apiVersion: v1
kind: Service
metadata:
  name: jgroups-gossip
  labels:
    app: infinispan
    role: discovery
spec:
  ports:
  - port: 12001
    targetPort: 12001
  selector:
    role: discovery
    app: infinispan
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jgroups-gossip
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: infinispan
        role: discovery
    spec:
      containers:
      - name: jgroups-gossip
        image: jboss/jgroups-gossip
        ports:
        - containerPort: 12001
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: infinispan-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: infinispan
        role: datanode
    spec:
      containers:
      - name: infinispan-server
        image: jboss/infinispan-server
        args:
        - custom/my-config
        - "-Djboss.default.jgroups.stack=tcp-gossip"
        - "-Djgroups.gossip.initial_hosts=$(JGROUPS_GOSSIP_SERVICE_HOST)[$(JGROUPS_GOSSIP_PORT_12001_TCP_PORT)]"
        volumeMounts: 
          - name: config-volume
            mountPath: /opt/jboss/infinispan-server/standalone/configuration/custom/
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8181
        - containerPort: 8888
        - containerPort: 9990
        - containerPort: 11211
        - containerPort: 11222
      volumes:
      - name: config-volume
        configMap:
          name: infinispan-config
